# Generated by Django 4.2.4 on 2023-10-19 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='compétences',
            name='competence',
            field=models.CharField(default='JS', max_length=100, unique=True),
        ),
    ]
