# Generated by Django 4.2.4 on 2023-10-19 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_compétences_competence'),
    ]

    operations = [
        migrations.CreateModel(
            name='Experience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('poste', models.CharField(max_length=100)),
                ('entreprise', models.CharField(max_length=100)),
                ('contrat', models.CharField(max_length=100)),
                ('data_commencement', models.DateField()),
                ('lieu', models.CharField(max_length=100)),
                ('image_entreprise', models.ImageField(blank=True, null=True, upload_to='images')),
                ('description', models.TextField()),
                ('crete_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
