# Generated by Django 4.2.4 on 2023-10-19 17:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_experience'),
    ]

    operations = [
        migrations.RenameField(
            model_name='experience',
            old_name='crete_at',
            new_name='created_at',
        ),
    ]
